import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sen } from 'next/font/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sen = Sen({
  subsets: ['latin'],
  weight: ['400' , '700']
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sen.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
